spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mybatis"
    username: "root"
    password: "111111"
  security:
    user:
      password: "111111"
      name: "admin"
  web:
    resources:
      static-locations: classpath:static/,classpath:/templates/

#security:
#  user:
#    name: "admin"
#    password: "111111"
